name: Build

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: 
      - created

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: 16
          distribution: adopt
          cache: gradle

      - name: Build with Gradlew
        run: |
          chmod +x ./gradlew
          ./gradlew build buildPlugin
          cp build/mirai/* build/libs

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          path: build/libs

      - name: Upload Build Space
        uses: actions/upload-artifact@v3
        with:
          name: buildspace
          path: ./

      - name: Upload Release
        uses: fnkr/github-action-ghr@v1
        if: github.event_name == 'release'
        env:
          GHR_PATH: build/libs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
